name: Slipstream Deploy
description: Request artifact deployment via Slipstream
inputs:
  environment:
    description: Environment to deploy to
    required: true
  service:
    description: Service to deploy
    required: true
  id:
    description: ID of artifact to deploy, e.g. image digest, files sha, module digest.
    required: true
  slipstream-cli-url:
    description: URL of the slipstream binary to download
    required: false
    default: https://bin.equinox.io/c/cXopLpzLbWK/slipstream-beta-linux-amd64.tgz

runs:
  using: node12
  main: dist/index.js
