name: Slipstream Push Image
description: Build and push image and metadata to Slipstream
inputs:
  dockerFile:
    description: Path to Dockerfile
    required: false
    default: Dockerfile
  contextPath:
    description: Path to Docker context. Probably the same directory as Dockerfile is in
    required: false
    default: '.'
  service:
    description: Service name for the artifact
    required: true
  labels:
    description: Comma separated key=value labels
    required: false
outputs:
  imageDigest:
    description: The image digest of the Docker image. Can be used to request a deployment.
runs:
  using: node12
  main: dist/index.js
