name: Cleanup Webapp
on:
  push:
    branches:
      main
    paths:
    - 'cleanup-webapp/**'
    - '.github/workflows/cleanup-webapp-*'
    - 'lib'
  pull_request:
    paths:
    - 'cleanup-webapp/**'
    - '.github/workflows/cleanup-webapp-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - run: npm ci
    - run: npm test --workspace cleanup-webapp

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-webapp
        with:
          service: webapp-action-integration-test
          staticRoot: ./.github/.fixtures
          indexFile: index.html
          artifactBucket: gs://bw-ee-labs-slipstream-github-action-test
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test
          prBuild: true
          prNumber: 123

      - uses: ./cleanup-webapp
        id: cleanup
        with:
          service: webapp-action-integration-test
          artifactBucket: gs://bw-ee-labs-slipstream-github-action-test
          version: 123

      - name: Deletion not Skipped
        run: "[[ \"${{steps.cleanup.outputs.skipped}}\" == \"false\" ]]"

