name: deploy test
on:
  push:
    paths:
    - 'deploy/**'
    - '.github/workflows/deploy-*'
  pull_request:
    paths:
    - 'deploy/**'
    - '.github/workflows/deploy-*'

jobs:
  run:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: npm install
      run: npm install
      working-directory: ./deploy

    - name: npm test
      run: npm test
      working-directory: ./deploy
