name: Deploy
on:
  push:
    branches:
      main
    paths:
    - 'deploy/**'
    - '.github/workflows/deploy-*'
    - 'lib'
  pull_request:
    paths:
    - 'deploy/**'
    - '.github/workflows/deploy-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - run: npm ci
  integration:
    name: Integration Test
    #needs: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
        create_credentials_file: true

    - uses: actions/setup-node@v3
      with:
        node-version: 12.x
    - uses: google-github-actions/setup-gcloud@v0
    - uses: ./install-cli

    - name: Start fake slipstream API
      run: node scripts/fake-slipstream-server.js &
      working-directory: ./deploy

    - name: Create config file
      run : |
        mkdir -p ${HOME}/.slipstream/
        cat <<EOF > ${HOME}/.slipstream/config.yaml
        apiurl: http://localhost:3000
        EOF

    - name: Run deploy action
      uses: ./deploy
      with:
        environment: stage
        service: myservice
        id: 1234
