name: Install CLI
on:
  push:
    branches:
      main
    paths:
    - 'install-cli/**'
    - '.github/workflows/install-cli-*'
    - 'lib'
  pull_request:
    paths:
    - 'install-cli/**'
    - '.github/workflows/install-cli-*'
    - 'lib'

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
        create_credentials_file: true
    - uses: ./install-cli
    # Needs this because the version command can't run without. We should fix that.
    - uses: google-github-actions/setup-gcloud@v0
    - run: slipstream version
