name: Install CLI
on:
  push:
    branches:
      main
    paths:
    - 'install-cli/**'
    - '.github/workflows/install-cli-*'
    - 'lib'
  pull_request:
    paths:
    - 'install-cli/**'
    - '.github/workflows/install-cli-*'
    - 'lib'

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./install-cli
    # Needs this because the version command can't run without. We should fix that.
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
        export_default_credentials: true
    - run: slipstream version
