name: Lib
on:
  push:
    branches:
      main
    paths:
    - 'lib/**'
    - '.github/workflows/lib-*'
    - 'lib'
  pull_request:
    paths:
    - 'lib/**'
    - '.github/workflows/lib-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@main
      with:
        node-version-file: .nvmrc
    - run: npm install
