name: Push Image
on:
  push:
    branches:
      main
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'
  pull_request:
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./lib
    - run: npm install
      working-directory: ./push-image
    - run: npm test
      working-directory: ./push-image
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_key: ${{ secrets.BW_PROD_ARTIFACTS_KEY }}
          export_default_credentials: true
      - uses: ./push-image
        with:
          dockerFile: test-fixtures/Dockerfile
          contextPath: test-fixtures
          service: action-integration-test
          dockerRegistry: eu.gcr.io/bw-stage-slipstream0
          metadataBucket: gs://slipstream-github-action-test
