name: Push Files
on:
  push:
    branches:
    - main
    paths:
    - 'push-files/**'
    - '.github/workflows/push-files-*'
    - 'lib'
  pull_request:
    paths:
    - 'push-files/**'
    - '.github/workflows/push-files-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - run: npm ci
    - run: npm test --workspace push-files

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true

      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-files
        with:
          service: files-action-integration-test
          filesDir: ./.github/.fixtures
          stageVersionCheckURL: https://whatever.com
          productionVersionCheckURL: https://whatever.com
          artifactBucket: gs://bw-ee-labs-slipstream-github-action-test
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@main
      with:
        node-version-file: .nvmrc
    - run: npm ci
    - run: npm run build --workspace push-files
    - run: ./scripts/assert-git-clean.sh

