name: Push Image
on:
  push:
    branches:
      main
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'
  pull_request:
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version-file: .nvmrc
    - run: npm install # In the root for shared dev deps
    - run: npm install
      working-directory: ./lib
    - run: npm install
      working-directory: ./push-image
    - run: npm test
      working-directory: ./push-image
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-image
        with:
          dockerfile: test-fixtures/Dockerfile
          path: test-fixtures
          service: action-integration-test
          pull: true,
          buildArgs: k1=v1,k2=v2
          dockerRegistry: eu.gcr.io/bw-ee-labs
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test
