name: Push Image
on:
  push:
    branches:
      main
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'
  pull_request:
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - run: npm ci
    - run: npm test --workspace push-image

  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-image
        with:
          dockerfile: test-fixtures/Dockerfile
          path: test-fixtures
          service: action-integration-test
          pull: true,
          buildArgs: k1=v1,k2=v2
          dockerRegistry: eu.gcr.io/bw-ee-labs
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test

  integration-aws:
    name: Integration Test (AWS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-image
        with:
          dockerfile: test-fixtures/Dockerfile
          path: test-fixtures
          service: action-integration-test
          pull: true,
          buildArgs: k1=v1,k2=v2
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test
          labels: project=appinfra
          dockerRegistry: 965748740018.dkr.ecr.eu-west-1.amazonaws.com
          release: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_PROD_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_PROD_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@main
      with:
        node-version-file: .nvmrc
    - run: npm ci
    - run: npm run build --workspace push-image
    - run: ./scripts/assert-git-clean.sh
