name: Push Module
on:
  push:
    branches:
      [main]
    paths:
    - 'push-module/**'
    - '.github/workflows/push-module-*'
    - 'lib'
  pull_request:
    paths:
    - 'push-module/**'
    - '.github/workflows/push-module-*'
    - 'lib'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@master
      with:
        node-version-file: .nvmrc
    - run: npm install
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.BW_EE_LABS_REGISTRY_KEY }}
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./push-module
        with:
          bundleId: test-app1
          version: 0.1.1-SNAPSHOT
          metadataBucket: gs://bw-ee-labs-slipstream-github-action-test
