name: Test Push Image Action
on:
  push:
    branches:
      master
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'
  pull_request:
    paths:
    - 'push-image/**'
    - '.github/workflows/push-image-*'

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./lib
    - run: npm install
      working-directory: ./push-image
    - run: npm test
      working-directory: ./push-image
